mode: sim           # sim | serial
serial:
  port: "COM5"      # e.g., /dev/ttyUSB0 on Linux
  baud: 9600
sampling_hz: 5
calibration_seconds: 12
smooth:
  type: "ema"       # ema | ma
  ema_alpha: 0.20
  ma_window: 8
threshold:
  k_sigma: 3.0
  hysteresis: 0.5
ppm:
  enabled: false
  rs_r0: 1.0        # set if available from circuit
output:
  save_csv: "data/sample_sim.csv"
  make_plot: true
  plot_path: "data/plot.png"
